### ISSUE TITLE
Crash due to OutOfMemoryError

### ISSUE THREAD

**Issue by emanuele-f** [emanuele-f/PCAPdroid#167]
Some users are experiencing OutOfMemoryError crashes in the latest PCAPdroid version. This occurs both in the f-droid and the playstore version. This may be a result of some memory/resource leak or increased memory usage (e.g. due to geolocation lookups). This should be investigated.

Here are some stack traces:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.emanuelef.remote_capture/com.emanuelef.remote_capture.activities.MainActivity}: android.view.InflateException: Binary XML file line #27 in com.emanuelef.remote_capture:layout/main_activity: Binary XML file line #27 in com.emanuelef.remote_capture:layout/main_activity: Error inflating class <unknown>
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3835)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4011)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:246)
at android.app.ActivityThread.main(ActivityThread.java:8633)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: android.view.InflateException: Binary XML file line #27 in com.emanuelef.remote_capture:layout/main_activity: Binary XML file line #27 in com.emanuelef.remote_capture:layout/main_activity: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #27 in com.emanuelef.remote_capture:layout/main_activity: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.newInstance0(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
at android.view.LayoutInflater.createView(LayoutInflater.java:852)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:706)
at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
at com.emanuelef.remote_capture.activities.MainActivity.onCreate(MainActivity.java:116)
at android.app.Activity.performCreate(Activity.java:8207)
at android.app.Activity.performCreate(Activity.java:8191)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3808)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4011)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:246)
at android.app.ActivityThread.main(ActivityThread.java:8633)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available
```

```
Caused by: java.lang.OutOfMemoryError: 
  at dalvik.system.VMRuntime.newNonMovableArray (Native Method)
  at android.graphics.BitmapFactory.nativeDecodeAsset (Native Method)
  at android.graphics.BitmapFactory.decodeStream (BitmapFactory.java:747)
  at android.graphics.BitmapFactory.decodeResourceStream (BitmapFactory.java:568)
  at android.graphics.drawable.Drawable.createFromResourceStream (Drawable.java:1014)
  at android.content.res.Resources.loadDrawableForCookie (Resources.java:3747)
  at android.content.res.Resources.loadDrawable (Resources.java:3620)
  at android.content.res.Resources.getDrawable (Resources.java:1852)
  at android.content.res.Resources.getDrawable (Resources.java:1818)
  at android.app.ApplicationPackageManager.getDrawable (ApplicationPackageManager.java:833)
  at android.app.ApplicationPackageManager.loadUnbadgedItemIcon (ApplicationPackageManager.java:2061)
  at android.app.ApplicationPackageManager.loadItemIcon (ApplicationPackageManager.java:2039)
  at android.content.pm.PackageItemInfo.loadIcon (PackageItemInfo.java:216)
  at com.emanuelef.remote_capture.model.AppDescriptor.getIcon (AppDescriptor.java:82)
  at com.emanuelef.remote_capture.AppsLoader.asyncLoadAppsIcons (AppsLoader.java:101)
  at com.emanuelef.remote_capture.AppsLoader.access$100 (AppsLoader.java:42)
  at com.emanuelef.remote_capture.AppsLoader$1.loadInBackground (AppsLoader.java:131)
  at com.emanuelef.remote_capture.AppsLoader$1.loadInBackground (AppsLoader.java:110)
  at androidx.loader.content.AsyncTaskLoader.onLoadInBackground (AsyncTaskLoader.java:307)
  at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground (AsyncTaskLoader.java:60)
  at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground (AsyncTaskLoader.java:48)
  at androidx.loader.content.ModernAsyncTask$2.call (ModernAsyncTask.java:141)
  at java.util.concurrent.FutureTask.run (FutureTask.java:237)
```

**Comment by emanuele-f** [comment]
No feedback received, will reopen if necessary.
