### ISSUE TITLE
App crashes on Android permissions reset

### ISSUE THREAD

**Issue by kevin0t** [emanuele-f/PCAPdroid#431]
Recently i did a reset of android permissions to default by going into settings>system>reset options>reset app preferences , as some system apps like webview were not working well , possibly due to some permission issues. On doing this the pcapdroid app crashed instead of asking for vpn permission again. There might be a possibility of some bugs in the OS itself in this regard.

crash log -

```
Build type: fdroid
Build version: 1.7.1
Build date: 2024-03-30 08:59:22
Current date: 2024-04-16 12:32:05
Device: motorola moto g82 5G
OS version: Android 13 (SDK 33)

Stack trace:
android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service com.emanuelef.remote_capture/.VpnReconnectService
at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
at android.os.Parcel.readParcelableInternal(Parcel.java:4792)
at android.os.Parcel.readParcelable(Parcel.java:4760)
at android.os.Parcel.createExceptionOrNull(Parcel.java:3023)
at android.os.Parcel.createException(Parcel.java:3012)
at android.os.Parcel.readException(Parcel.java:2995)
at android.os.Parcel.readException(Parcel.java:2937)
at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:5896)
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1914)
at android.app.ContextImpl.startForegroundService(ContextImpl.java:1890)
at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:1091)
at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:749)
at com.emanuelef.remote_capture.CaptureService.updateServiceStatus(CaptureService.java:1423)
at com.emanuelef.remote_capture.CaptureService.lambda$run$3$com-emanuelef-remote_capture-CaptureService(CaptureService.java:1146)
at com.emanuelef.remote_capture.CaptureService$$ExternalSyntheticLambda13.run(Unknown Source:2)
at android.os.Handler.handleCallback(Handler.java:984)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loopOnce(Looper.java:238)
at android.os.Looper.loop(Looper.java:357)
at android.app.ActivityThread.main(ActivityThread.java:8088)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)

DumpMode: NONE
FullPayload: false
TLSDecryption: false
TLSSetupOk: false
CAInstallSkipped: false
BlockQuic: NEVER
RootCapture: false
Socks5: false
BlockPrivateDns: false
CaptureInterface: @inet
MalwareDetection: true
Firewall: true
PCAPNG: true
BlockNewApps: true
TargetApps: []
IpMode: IPV4_ONLY
Trailer: false
StartAtBoot: true
```

**Comment by emanuele-f** [comment]
@kevin0t is this issue still happening?
