### ISSUE TITLE
can't compile this app cause of problem with command: System.loadLibrary("vpnproxy-jni");

### ISSUE THREAD

**Issue by shilogav** [emanuele-f/PCAPdroid#75]
Hi, 
I'm new at this app and trying to compile it but face with crash, this is the log:

E/CustomActivityOnCrash: The previous app process crashed. This is the stack trace of the crash:
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.emanuelef.remote_capture-QR5mNpfoMwalm_T060NAGQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.emanuelef.remote_capture-QR5mNpfoMwalm_T060NAGQ==/lib/x86, /system/lib]]] couldn't find "libvpnproxy-jni.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.emanuelef.remote_capture.CaptureService.<clinit>(CaptureService.java:126)
        at com.emanuelef.remote_capture.CaptureService.isServiceActive(CaptureService.java:483)
        at com.emanuelef.remote_capture.activities.MainActivity.initAppState(MainActivity.java:498)
        at com.emanuelef.remote_capture.activities.MainActivity.onCreate(MainActivity.java:120)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

thanks!

**Comment by emanuele-f** [comment]
Weird issue, did you made modifications to the source? Are you using the latest master? Have you tried starting from scratch by following the instructions at https://github.com/emanuele-f/PCAPdroid#building ?

**Comment by shilogav** [comment]
wow, I really appreciate the fast response.
I didn't say I'm using windows. I use that android apps are cross platform, I guess that you write that it meant to work with linux is because of the C++ files.
I'll move to ubuntu as you said. my mistake
